# Generated by Django 3.1.8 on 2022-02-25 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time & Day')),
                ('stop_time', models.DateTimeField(verbose_name='Stop Time & Day')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OCS Officer')),
                ('police_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile', verbose_name='Police Officer')),
            ],
            options={
                'verbose_name_plural': 'Shifts',
            },
        ),
    ]
