# Generated by Django 3.1.8 on 2022-02-22 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accused', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_number', models.CharField(max_length=255, verbose_name='Cell Number.')),
                ('cell_status', models.CharField(choices=[('Occupied', 'Occupied'), ('Empty', 'Empty')], max_length=50, verbose_name='Cell Status')),
                ('occupied_on', models.DateField(verbose_name='Occupied On')),
                ('vaccated_on', models.DateField(verbose_name='Vaccated On')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('accused_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accused.accusedperson', verbose_name='Accused Person')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Police Officer')),
            ],
            options={
                'verbose_name_plural': 'Cells',
            },
        ),
    ]
