# Generated by Django 3.1.8 on 2022-02-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accused', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=255, verbose_name='Arrest Number.')),
                ('cause_of_arrest', models.TextField(max_length=254, verbose_name='Cause Of Arrest')),
                ('crime_category', models.CharField(choices=[('Arson', 'Arson'), ('Armed Robbery', 'Armed Robbery'), ('Assault', 'Assault'), ('Burglary', 'Burglary'), ('Carjacking', 'Carjacking'), ('Cattle Rustling', 'Cattle Rustling'), ('Corruption', 'Corruption'), ('Drug Abuse', 'Drug Abuse'), ('Drug Trafficking', 'Drug Trafficking'), ('Embezzlement', 'Embezzlement'), ('Fraud', 'Fraud'), ('Homicide', 'Homicide'), ('Human trafficking', 'Human trafficking'), ('Kidnapping', 'Kidnapping'), ('Mob Justice', 'Mob Justice'), ('Money Laundering', 'Money Laundering'), ('Massive Looting', 'Massive Looting'), ('Petty Theft', 'Petty Theft'), ('Pickpocketing', 'Pickpocketing'), ('Rape', 'Rape'), ('Terrorism', 'Terrorism')], max_length=50, verbose_name='Crime Category')),
                ('arrest_location', models.CharField(max_length=50, verbose_name='Arrest Location')),
                ('case_started_on', models.DateField(verbose_name='Case Started On')),
                ('case_concluded_on', models.DateField(blank=True, null=True, verbose_name='Case Concluded On')),
                ('case_status', models.CharField(choices=[('Not Started', 'Not Started'), ('Ongoing', 'Ongoing'), ('Complete', 'Complete')], max_length=50, verbose_name='Case Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('accused_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accused.accusedperson', verbose_name='Accused Person')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile', verbose_name='Police Officer')),
            ],
            options={
                'verbose_name_plural': 'Cases',
            },
        ),
    ]
