# Generated by Django 3.1.8 on 2022-02-22 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accused', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=255, verbose_name='Arrest Number.')),
                ('cause_of_arrest', models.TextField(max_length=254, verbose_name='Cause Of Arrest')),
                ('crime_category', models.CharField(choices=[('Arson', 'Arson'), ('Armed Robbery', 'Armed Robbery'), ('Assault', 'Assault'), ('Burglary', 'Burglary'), ('Carjacking', 'Carjacking'), ('Cattle Rustling', 'Cattle Rustling'), ('Corruption', 'Corruption'), ('Drug Abuse', 'Drug Abuse'), ('Drug Trafficking', 'Drug Trafficking'), ('Embezzlement', 'Embezzlement'), ('Fraud', 'Fraud'), ('Homicide', 'Homicide'), ('Human trafficking', 'Human trafficking'), ('Kidnapping', 'Kidnapping'), ('Mob Justice', 'Mob Justice'), ('Money Laundering', 'Money Laundering'), ('Massive Looting', 'Massive Looting'), ('Petty Theft', 'Petty Theft'), ('Pickpocketing', 'Pickpocketing'), ('Rape', 'Rape'), ('Terrorism', 'Terrorism')], max_length=50, verbose_name='Crime Category')),
                ('arrest_location', models.CharField(max_length=50, verbose_name='Arrest Location')),
                ('police_station', models.CharField(blank=True, choices=[('Central Police Station', 'Central Police Station'), ('Kilimani Police Station', 'Kilimani Police Station'), ('Embakasi Police Station', 'Embakasi Police Station'), ("Lang'ata Police Station", "Lang'ata Police Station"), ("Ong'ata Rongai Police Station", "Ong'ata Rongai Police Station"), ('Buruburu Police Station', 'Buruburu Police Station'), ('Kasarani Police Station', 'Kasarani Police Station'), ('Parklands Police Station', 'Parklands Police Station'), ('Pangani Police Station', 'Pangani Police Station'), ('Muthaiga Police Station', 'Muthaiga Police Station')], max_length=150, null=True, verbose_name='Police Station')),
                ('county', models.CharField(choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma ', 'Bungoma '), ('Busia', 'Busia'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Marsabit', 'Marsabit'), ('Mombasa', 'Mombasa'), ('Muranga', 'Muranga'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita Taveta', 'Taita Taveta'), ('Tana River', 'Tana River'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], max_length=100, verbose_name='County')),
                ('case_started_on', models.DateField(verbose_name='Case Started On')),
                ('case_concluded_on', models.DateField(verbose_name='Case Concluded On')),
                ('case_status', models.CharField(choices=[('Not Started', 'Not Started'), ('Ongoing', 'Ongoing'), ('Complete', 'Complete')], max_length=50, verbose_name='Case Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('accused_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accused.accusedperson', verbose_name='Accused Person')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Police Officer')),
            ],
            options={
                'verbose_name_plural': 'Cases',
            },
        ),
    ]
