# Generated by Django 3.1.8 on 2022-02-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccusedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrest_number', models.CharField(max_length=255, verbose_name='Arrest Number.')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender')),
                ('national_id', models.CharField(max_length=10, verbose_name='National ID')),
                ('profile_picture', models.ImageField(upload_to='Accused-Profile-Pics', verbose_name='Accused Person Profile Pics')),
                ('arrest_status', models.CharField(choices=[('Free', 'Free'), ('Convicted', 'Convicted'), ('In Cutody', 'In Cutody'), ('Out On Bond', 'Out On Bond'), ('Out On Cash Bail', 'Out On Cash Bail')], max_length=50, verbose_name='Arrest Status')),
                ('arrested_on', models.DateField(verbose_name='Arrested On')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile', verbose_name='Police Officer')),
            ],
            options={
                'verbose_name_plural': 'Accused Persons Profiles',
            },
        ),
    ]
