# Generated by Django 3.1.8 on 2022-02-20 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=10, verbose_name='Middle Name')),
                ('bio', models.TextField(max_length=254, verbose_name='Bio')),
                ('national_id', models.CharField(max_length=10, verbose_name='National ID')),
                ('profile_picture', models.ImageField(upload_to='Profile-Pics', verbose_name='Profile-Pics')),
                ('police_station', models.CharField(blank=True, choices=[('Central Police Station', 'Central Police Station'), ('Kilimani Police Station', 'Kilimani Police Station'), ('Embakasi Police Station', 'Embakasi Police Station'), ("Lang'ata Police Station", "Lang'ata Police Station"), ("Ong'ata Rongai Police Station", "Ong'ata Rongai Police Station"), ('Buruburu Police Station', 'Buruburu Police Station'), ('Kasarani Police Station', 'Kasarani Police Station'), ('Parklands Police Station', 'Parklands Police Station'), ('Pangani Police Station', 'Pangani Police Station'), ('Muthaiga Police Station', 'Muthaiga Police Station')], max_length=150, null=True, verbose_name='Police Station')),
                ('role', models.CharField(default='Police Officer', max_length=20, verbose_name='Role')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed?')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Officer Profiles',
            },
        ),
        migrations.CreateModel(
            name='OCSProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=10, verbose_name='Middle Name')),
                ('bio', models.TextField(max_length=254, verbose_name='Bio')),
                ('national_id', models.CharField(max_length=10, verbose_name='National ID')),
                ('profile_picture', models.ImageField(upload_to='Profile-Pics', verbose_name='Profile-Pics')),
                ('police_station', models.CharField(blank=True, choices=[('Central Police Station', 'Central Police Station'), ('Kilimani Police Station', 'Kilimani Police Station'), ('Embakasi Police Station', 'Embakasi Police Station'), ("Lang'ata Police Station", "Lang'ata Police Station"), ("Ong'ata Rongai Police Station", "Ong'ata Rongai Police Station"), ('Buruburu Police Station', 'Buruburu Police Station'), ('Kasarani Police Station', 'Kasarani Police Station'), ('Parklands Police Station', 'Parklands Police Station'), ('Pangani Police Station', 'Pangani Police Station'), ('Muthaiga Police Station', 'Muthaiga Police Station')], max_length=150, null=True, verbose_name='Police Station')),
                ('role', models.CharField(default='Officer Commanding Station', max_length=20, verbose_name='Role')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed?')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'OCS Profiles',
            },
        ),
    ]
