# Generated by Django 3.1.8 on 2022-02-24 18:35

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender')),
                ('middle_name', models.CharField(max_length=10, verbose_name='Middle Name')),
                ('bio', models.TextField(max_length=254, verbose_name='Bio')),
                ('national_id', models.CharField(max_length=10, verbose_name='National ID')),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_picture')),
                ('police_station', models.CharField(blank=True, choices=[('Central Police Station', 'Central Police Station'), ('Kilimani Police Station', 'Kilimani Police Station'), ('Embakasi Police Station', 'Embakasi Police Station'), ("Lang'ata Police Station", "Lang'ata Police Station"), ("Ong'ata Rongai Police Station", "Ong'ata Rongai Police Station"), ('Buruburu Police Station', 'Buruburu Police Station'), ('Kasarani Police Station', 'Kasarani Police Station'), ('Parklands Police Station', 'Parklands Police Station'), ('Pangani Police Station', 'Pangani Police Station'), ('Muthaiga Police Station', 'Muthaiga Police Station')], max_length=150, null=True, verbose_name='Police Station')),
                ('role', models.CharField(choices=[('Police Officer', 'Police Officer'), ('Officer Commanding Station', 'Officer Commanding Station')], max_length=100, verbose_name='Role')),
                ('county', models.CharField(choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma ', 'Bungoma '), ('Busia', 'Busia'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Marsabit', 'Marsabit'), ('Mombasa', 'Mombasa'), ('Muranga', 'Muranga'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita Taveta', 'Taita Taveta'), ('Tana River', 'Tana River'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], max_length=100, verbose_name='County')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed?')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Officer Profiles',
            },
        ),
    ]
